server:
  port: 8989
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: api-gateway
  tracing:
    enabled: false
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/catalog/**
              filters:
                - RewritePath=/catalog/?(?<segment>.*), /${segment}
#http://localhost:8989/catalog/api/products -> http://localhost:8082//api/products
            - id: orders-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/orders/**
              filters:
                - RewritePath=/orders/?(?<segment>.*), /${segment}
            - id: openapi
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                allow-credentials: false
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST

  mvc:
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
#      - name: catalog
#        url: /v3/api-docs/catalog
#      - name: orders
#        url: /v3/api-docs/orders