name: Notification Service
on:
  push:
    paths:
      - notification-service/**
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./notification-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean -ntp verify -DskipTests


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish Docker Image
        run: |
          ./mvnw clean spring-boot:build-image -DskipTests
          docker push harivara/bookstore-notification-service
